version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1.2

executors:
  docker-executor:
    docker:
      - image: cimg/base:2022.04

jobs:
  shellcheck:
    parameters:
      bashdir:
        type: string
        default: .
      ExcludeedList:
        type: string
        default: SC2027,SC2046,SC1091
    executor: docker-executor
    resource_class: small
    steps:
      - checkout          
      - shellcheck/check:
          dir: << parameters.bashdir >>
          exclude: << parameters.ExcludeedList >>

workflows:
  shell-check:
    jobs:
      - shellcheck